Create tmpdir if it does not exist
mittwald/salt-percona-formula pull request #4
Opened 2016-12-08 11:07 UTC by Takios

If 'tmpdir' is given in pillar, make sure that it exists.
MySQL refuses to start if the directory does not exist

2016-12-08 11:53 UTC, martin-helmich requested changes

2016-12-08 11:53 UTC, martin-helmich commented on percona/config.sls
> +{% endif %}
If the default value is `/tmp`, we should not change ownership to `mysql:mysql` with `0775`

2016-12-08 12:13 UTC, Takios commented on percona/config.sls
> +{% endif %}
Done. I am now only setting the mode to 777. `/tmp` should be 777 everywhere.

2016-12-08 12:16 UTC, martin-helmich approved these changes

2016-12-08 12:45 UTC, luitzifa requested changes
The correct mode for an tmp directory is 1777. The sticky bit will prevent users from deleting files of other users in this directory.

2016-12-09 08:37 UTC, Takios commented
@luitzifa That makes sense. I updated the commit so it sets the mode to 1777.

2016-12-09 08:54 UTC, luitzifa approved these changes

2016-12-09 08:54 UTC, merged